#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
# Real-device acceptance for the hanoi project (ticket 01), following the
# official guide "使用真机调试运行应用":
#   https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/ide-run-device
# Flow: developer mode + USB debugging on the phone → connect & authorize
# (MTP) → AGC app exists (bundleName match) → DevEco automatic signing →
# wizard builds/installs/launches/verifies via hdc.
# Works on any host (Intel Mac included) — unlike the arm64-only emulator.

TOTAL_STAGES=7

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEVECO_HOME="/Applications/DevEco-Studio.app"
SDK="$DEVECO_HOME/Contents/sdk"
HDC="$SDK/default/openharmony/toolchains/hdc"
BUNDLE="com.example.hanoi"
ABILITY="EntryAbility"

banner "HarmonyOS real-device setup — hanoi"

# ── Stage 1: phone developer mode ─────────────────────────────────────────
stage "Phone — developer mode"
say "On the HarmonyOS phone:"
step "设置 (Settings) → 通用 (General) → 关于手机 (About phone)"
step "Tap 版本号 (Build number) seven times until it says 开发者模式已开启."
step "Back in 设置 → 通用 → 开发者模式 (Developer options): turn it ON."
pause "Press Enter once developer mode is on."

# ── Stage 2: USB debugging on the phone ───────────────────────────────────
stage "Phone — USB debugging"
step "设置 → 通用 → 开发者模式: enable 开启 USB 调试 (USB debugging)."
step "Also enable 允许 USB 安装 (allow USB installs) if present, so hdc can"
step "  push the HAP without an extra prompt."
note "If the device was previously connected with ADB, disconnect/reconnect USB."
pause "Press Enter once USB debugging is on."

# ── Stage 3: connect & authorize, then let hdc see it ─────────────────────
stage "Connect & authorize"
step "Plug the phone into this computer with a USB cable."
step "On the phone, in the USB-usage dialog choose 文件传输 (File transfer / MTP)."
step "On this computer, allow the debug-authorization popup and tick"
step "  'Always allow this computer' if offered (computer-side: last step of"
step "  the hdc pairing prompt is '始终允许此计算机调试')."
say "Waiting for hdc to see the device…"
TARGET=""
for _ in $(seq 1 30); do
  TARGET="$("$HDC" list targets 2>/dev/null | grep -v '^$' || true)"
  [[ -n "$TARGET" && ! "$TARGET" =~ ^\[Empty\] ]] && break
  sleep 4
done
if [[ -z "$TARGET" || "$TARGET" =~ ^\[Empty\] ]]; then
  warn "hdc still sees no device ($("$HDC" list targets 2>/dev/null | tr '\n' ' '))."
  warn "Re-check: USB debugging on? USB mode = File transfer? Authorized popup accepted?"
  confirm "Retry scanning for 2 more minutes?" || exit 1
  for _ in $(seq 1 30); do
    TARGET="$("$HDC" list targets 2>/dev/null | grep -v '^$' || true)"
    [[ -n "$TARGET" && ! "$TARGET" =~ ^\[Empty\] ]] && break
    sleep 4
  done
fi
note "✓ Device: $(echo "$TARGET" | tr '\n' ' ')"
pause

# ── Stage 4: AppGallery Connect app with the matching bundleName ──────────
stage "AGC app (bundleName must exist)"
say "Automatic signing provisions a debug profile keyed to the app"
say "${BUNDLE} — it must already exist on AppGallery Connect."
step "Project → app/元服务 with the exact bundle name ${BUNDLE}."
open_url "https://developer.huawei.com/consumer/cn/service/jsp/agc/index.html"
step "No real-name verification yet? You can still get a 14-day debug profile"
step "  from a real-name-verified, APP-manager (or higher) Huawei account."
pause "Press Enter once the AGC app exists (or you're sure you already have one)."

# ── Stage 5: DevEco automatic signing (human, in the IDE) ─────────────────
stage "DevEco — automatic signing"
say "Open this project in DevEco Studio (File > Open… → $REPO) "
say "and let it sign for debug with your Huawei account:"
step "File > Project Structure > Project > Signing Configs"
step "Tick 勾选 Automatically generate signature, then 登录 (Sign in) with the"
step "  Huawei account and 允许 (Allow) the authorization."
step "Wait until signing completes (it fetches cert + debug profile for this"
step "  device and writes them into build-profile.json5), then click OK."
note "Success looks like: a signingConfig named 'default' (material paths) "
note "appears in build-profile.json5, and the run device shows the phone."
pause "Press Enter once signing finished and you clicked OK."

# ── Stage 6: build, install, launch, verify (automatic) ───────────────────
stage "Build & install the signed app"
step "Building with the auto-signed config:"
(cd "$REPO" && ./hvigorw assembleHap --mode module -p product=default -p buildMode=debug) || {
  warn "Build failed — if it says 'no signing config', stage 5 didn't write"
  warn "signingConfigs into build-profile.json5 yet; re-run stage 5."
  exit 1; }
HAP="$(find "$REPO/entry/build/default/outputs" -name "*.hap" | head -1)"
note "✓ HAP: $HAP"
if ! "$HDC" install -r "$HAP" 2>/dev/null; then
  warn "Install failed — likely a signature error (真机要求已签名 HAP)."
  warn "Re-check stage 5 (auto-signing) and that the bundle name matches AGC,"
  warn "  then re-run this wizard — it remembers nothing, stages are idempotent."
  exit 1
fi
step "Launching ${BUNDLE}…"
"$HDC" shell aa start -a "$ABILITY" -b "$BUNDLE" || true
sleep 5
note "Process check (should print a PID):"
"$HDC" shell "pidof $BUNDLE" 2>/dev/null || true
say "Expected on the phone: the app opens a blank white page — 工单 01 的"
say "空主页面. DevEco's green ▶ Run button achieves the same thing."
pause

# ── Stage 7: done ─────────────────────────────────────────────────────────
stage "Wrap-up"
note "工单 01 真机验收完成:模拟器选项不再需要(Intel Mac 或 Apple Silicon 均可)。"
note "日常迭代:改代码后 ./hvigorw test(单测)+ 本向导第 6 阶段重装,或直接用"
note "DevEco 的 ▶ Run 到真机。"
pause

finish
note "If the emulator path is still wanted on an Apple Silicon Mac, use"
note "scripts/setup-emulator.sh instead."
