#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
# This wizard walks a human through the manual parts of "first-time setup" for
# the hanoi project (ticket 01): hardware check, DevEco Studio, emulator image
# download, AVD creation, and — if needed — automatic signing for real devices.
# Everything after the emulator is up (build, install, launch, verify) the
# wizard runs itself.
#
# Requirements the human must satisfy before running:
#   - A HarmonyOS emulator host: Apple Silicon macOS (arm64) or Windows x86_64
#     with Hyper-V. Intel macOS is NOT supported by the 6.x emulator images.
#     (This repo was scaffolded & verified on an Intel Mac where only the
#     build/test part can run headlessly.)
#   - DevEco Studio 6.x installed (bundles the HarmonyOS SDK + emulator).

TOTAL_STAGES=7

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEVECO_HOME="/Applications/DevEco-Studio.app"
HAP="entry/build/default/outputs/default/entry-default-unsigned.hap"
BUNDLE="com.example.hanoi"
ABILITY="EntryAbility"

# hdc_bin — the hdc CLI: from PATH, else the DevEco-bundled SDK toolchains.
hdc_bin() {
  command -v hdc 2>/dev/null || echo "$DEVECO_HOME/Contents/sdk/default/openharmony/toolchains/hdc"
}

banner "HarmonyOS emulator setup — hanoi"

# ── Stage 1: host hardware check (automatic; gates the rest) ──────────────
stage "Host capability check"
say "The HarmonyOS 6.x emulator ships arm64 images for macOS. Apple Silicon is"
say "required; Intel macOS cannot boot them. Windows works on x86_64 with Hyper-V."
if [[ "$(uname -s)" == "Darwin" ]]; then
  case "$(uname -m)" in
    arm64) note "✓ macOS arm64 (Apple Silicon) — emulator supported."
           ;;
    x86_64) warn "✗ Intel Mac detected: this machine cannot run the 6.1.1 emulator."
            warn "  The build/test pipeline (./hvigorw test + assembleHap) works here."
            warn "  Run this wizard on an Apple Silicon Mac, or accept via a real phone"
            warn "  (skip to the signing stage)."
            confirm "Continue for a real-device run instead?" || { say "Exiting. Bye."; exit 0; }
           ;;
  esac
elif [[ "$(uname -s)" == "Linux" || "$(uname -s)" == "MINGW"* || "$(uname -s)" == "MSYS"* ]]; then
  warn "Linux is not a HarmonyOS emulator host. Use macOS (Apple Silicon) or Windows."
  exit 1
fi
pause

# ── Stage 2: DevEco Studio present? ───────────────────────────────────────
stage "DevEco Studio"
if [[ -d "$DEVECO_HOME" ]]; then
  note "✓ Found $DEVECO_HOME"
else
  warn "DevEco Studio not found at $DEVECO_HOME."
  open_url "https://developer.huawei.com/consumer/cn/download/"
  step "Download & install DevEco Studio (HarmonyOS 6.x)."
  pause "Press Enter once it is installed."
fi
note "First launch: accept the HarmonyOS license agreements (Tools > SDK Manager)."
pause

# ── Stage 3: emulator image download (human, in the IDE) ──────────────────
stage "Emulator image (Device Manager)"
say "Open DevEco Studio, then Tools > Device Manager. This machine needs the"
say "phone image 'HarmonyOS 6.1.1(24)' (~2-3 GB download)."
open_url "https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/ide-emulator"
step "Device Manager → Device tab → phone → click the download icon next to"
step "  'HarmonyOS 6.1.1(24)' and let it finish. Requires a Huawei account login."
pause "Press Enter once the image is downloaded."

# ── Stage 4: create the phone AVD (optional; also auto-created) ───────────
stage "Create the phone device"
step "In Device Manager, click + (New Device) or run the downloaded image."
step "Pick 'Huawei_Phone' (defaults are fine) → Finish."
note "If Device Manager already auto-created a phone device, skip this stage."
pause "Press Enter once a phone device exists."

# ── Stage 5: boot the emulator, wait for hdc ──────────────────────────────
stage "Boot the emulator"
step "Device Manager → on the phone device click ▶ (Start)."
note "The window opens a full phone UI; first boot can take a couple of minutes."
if [[ -x "$(hdc_bin)" ]]; then
  HDC="$(hdc_bin)"
  pause "Press Enter once the phone UI is visible — the wizard waits for hdc…"
  for _ in $(seq 1 30); do
    if "$HDC" list targets 2>/dev/null | grep -qi "emulator\|phone"; then
      note "✓ hdc sees a target: $("$HDC" list targets 2>/dev/null | tr '\n' ' ')"
      break
    fi
    sleep 4
  done
else
  note "hdc not found on PATH — continue manually; install/launch steps below"
  note "will need the hdc from the SDK toolchains folder."
fi
pause

# ── Stage 6: build, install, launch, verify (automatic) ───────────────────
stage "Build & install the shell app"
step "Building the HAP (unsigned debug):"
(cd "$REPO" && ./hvigorw assembleHap --mode module -p product=default -p buildMode=debug) || {
  warn "Build failed — fix it first, then re-run this wizard."; exit 1; }
note "✓ HAP at $REPO/$HAP"
step "Installing via hdc:"
HDC="$(hdc_bin)"
"$HDC" install -r "$REPO/$HAP" || {
  warn "Install failed. Common causes:"
  warn "  • Emulator rejects the unsigned HAP → sign it (next stage), or use a"
  warn "    debug-signed build from DevEco (Run ▶ once)."
  warn "  • No target connected → start the emulator, re-run."
  exit 1; }
step "Launching $BUNDLE…"
"$HDC" shell aa start -a "$ABILITY" -b "$BUNDLE" || true
sleep 5
note "Target list & foreground check:"
"$HDC" list targets 2>/dev/null
"$HDC" shell "pidof $BUNDLE || echo 'process not found'" 2>/dev/null || true
say "Expected: the phone shows a blank white page (工单 01 的空主页面), and the"
say "app process for $BUNDLE is running."
pause

# ── Stage 7: signing (only for real devices / signed installs) ────────────
stage "Signing config (if needed)"
say "Only needed when installing on a real phone or when the emulator rejects"
say "the unsigned HAP. DevEco can auto-sign with your Huawei account."
step "File > Project Structure > Signing Configs"
step "Tick 'Automatically generate signature' → sign in to Huawei → Apply."
step "Then re-run stage 6 (the wizard re-installs the now-signed HAP)."
confirm "Did you configure signing (or is it not needed)?" || warn "Skipped."

finish
note "After this, ticket 01 acceptance is complete: emulator shows the empty"
note "main page; ./hvigorw test runs the Hypium empty assertion (already green)."
